#!/usr/bin/env bash
# Vendor the canonical TaskFast OpenAPI spec into spec/openapi.yaml and record
# its provenance in spec/openapi.provenance.toml.
#
# This is the ONLY supported way to update the vendored spec. Hand-editing
# spec/openapi.yaml will trip the spec-drift gate in CI (the recorded sha256 no
# longer matches the file).
#
# Requires: curl, sha256sum, git. Optionally uses `gh` (authenticated to the
# server repo) to record the exact server commit; degrades gracefully without.
#
# After running, regenerate the client and rebuild:
#   cargo xtask sync-spec && cargo build --workspace
set -euo pipefail

SPEC_URL="https://staging.taskfast.app/api/docs/spec"
SERVER_REPO="Akuja-Inc/taskfast"
SERVER_PATH="priv/openapi/agent-platform.yaml"

repo_root="$(git rev-parse --show-toplevel)"
spec_file="$repo_root/spec/openapi.yaml"
prov_file="$repo_root/spec/openapi.provenance.toml"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

echo "fetching $SPEC_URL ..."
curl -fsSL --max-time 60 -o "$tmp" "$SPEC_URL"

sha="$(sha256sum "$tmp" | cut -d' ' -f1)"
bytes="$(wc -c < "$tmp" | tr -d ' ')"

# Best-effort: resolve the server commit that last touched the canonical path.
# Needs `gh` authenticated with read access to the (private) server repo.
commit="unknown"
if command -v gh >/dev/null 2>&1; then
  commit="$(gh api "repos/$SERVER_REPO/commits?path=$SERVER_PATH&per_page=1" \
            --jq '.[0].sha' 2>/dev/null || echo unknown)"
fi

fetched="$(date -u +%Y-%m-%d)"

mv "$tmp" "$spec_file"
trap - EXIT

cat > "$prov_file" <<EOF
# Provenance of spec/openapi.yaml — generated by scripts/vendor-spec.sh.
# DO NOT EDIT BY HAND. The spec-drift CI gate and the scheduled upstream
# drift-check both compare against the sha256 recorded here. To refresh, re-run
# scripts/vendor-spec.sh (then: cargo xtask sync-spec && cargo build --workspace).
source        = "$SPEC_URL"
server_repo   = "$SERVER_REPO"
server_path   = "$SERVER_PATH"
server_commit = "$commit"
sha256        = "$sha"
bytes         = $bytes
fetched_at    = "$fetched"
EOF

echo "wrote $spec_file ($bytes bytes, sha256 ${sha:0:16}…)"
echo "wrote $prov_file (server_commit ${commit:0:12})"
echo "next: cargo xtask sync-spec && cargo build --workspace"
